# makes glib and gthread more portable

set(GLIB_REQUIRED_LIBS glib-2.0 gthread-2.0)
if (WIN32)
  if (NOT DEFINED ENV{GTK_PATH})
    message(FATAL_ERROR "ERROR: you must set the GTK_PATH environment variable")
  endif()
  include_directories($ENV{GTK_PATH}/include/glib-2.0)
  include_directories($ENV{GTK_PATH}/lib/glib-2.0/include)

  set(GLIB_LDFLAGS -LIBPATH:$ENV{GTK_PATH}/lib gthread-2.0.lib glib-2.0.lib ws2_32.lib winmm.lib) #intl.lib ole32.lib shlwapi.lib)
  install(FILES $ENV{GTK_PATH}/bin/libglib-2.0-0.dll DESTINATION lib)
  install(FILES $ENV{GTK_PATH}/bin/libgthread-2.0-0.dll DESTINATION lib)
  install(FILES $ENV{GTK_PATH}/bin/libintl-8.dll DESTINATION lib)  
  install(FILES $ENV{GTK_PATH}/bin/libiconv-2.dll DESTINATION lib)
  install(FILES $ENV{GTK_PATH}/bin/pthreadGC2.dll DESTINATION lib)
else()
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(GLIB glib-2.0 gthread-2.0)
  if (NOT GLIB_FOUND)
     message(FATAL_ERROR "ERROR: could not find glib-2.0 and/or gthread-2.0")
  endif()
  include_directories(${GLIB_INCLUDE_DIRS})
endif()

