set -e
CMAKE_VERSION_MAJOR=3
CMAKE_VERSION_MINOR=7
CMAKE_VERSION_PATCH=2
CMAKE_VERSION=$CMAKE_VERSION_MAJOR.$CMAKE_VERSION_MINOR.$CMAKE_VERSION_PATCH
pushd $HOME
curl -LO https://cmake.org/files/v$CMAKE_VERSION_MAJOR.$CMAKE_VERSION_MINOR/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
shasum -c $TRAVIS_BUILD_DIR/travis/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz.sha256
tar xf cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
rm -f cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
popd
export PATH=$HOME/cmake-$CMAKE_VERSION-Linux-x86_64/bin:$PATH
set +e
